import "./globals.css"
// import "./index.css"
// import "../styles/custom.css"
import { ThemeProvider } from "next-themes"
import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"
import { AuthProvider } from "@/contexts/auth"
import ErrorBoundary from "@/components/error-boundary"
// import { NextAuthProviders } from "@/components/auth/auth-provider"
// import { AuthProvider } from "@/contexts/auth"
// import { useThemeConfig } from "@/contexts/theme";

export const metadata = {
  title: "OpenHuman",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  // const themeConfig = useThemeConfig()

  return (
    <html lang="en" suppressHydrationWarning dir="ltr">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon.ico"></link>
        <meta
          name="description"
          content="OpenHuman"
        />
        <meta name="author" content="OpenHuman" />
        <title>OpenHuman</title>
      </head>
      <body className="nextra-banner-hidden">
        <ErrorBoundary>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <AuthProvider>
              <div dir="ltr">
                <Header />
                {children}
                <Footer />
              </div>
            </AuthProvider>
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  )
}
